service: newsletter-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: subscribe
          method: post

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env