Transform: AWS::Serverless-2016-10-31
Resources:
  NewsletterApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      Events:
        Subscribe:
          Type: Api
          Properties:
            Path: /subscribers
            Method: post